스프링 시큐리티 & firebase emulator 세팅하기
f-lab-edu/art-share pull request #13
Opened 2023-03-20 14:19 UTC by gimseonjin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature

## What is the current behavior?

Issue Number: #6 

## What is the new behavior?

## PR information

스프링 시큐리티와 firebase emulator를 세팅했습니다.

유저 및 토큰 관리에 힘쓰는 것 보다 다른 기능에 더 집중하고 싶어서 firebase auth를 사용하기로 했고 실제 product말고 firebase emulator를 사용하기로 했습니다.

관련 세팅은 docker-compose로 세팅했고 코드 변경을 감지해서 자동으로 컨테이너에 반영하도록 gradle 파일, docker volume, dev-tools를 세팅했습니다.

2023-03-23 12:33 UTC, f-lab-kyucumber requested changes

2023-03-23 12:33 UTC, f-lab-kyucumber commented on .editorconfig
> +[*.{kt,kts}]
trailing comma도 저는 있으면 편하더라고요.
생성자나 파라미터 추가할 때 콤마를 한번 더 찍을 필요가 없어져요.

2023-03-23 12:33 UTC, f-lab-kyucumber commented on build.gradle.kts
> +    annotationProcessor("org.projectlombok:lombok")
lombok은 코틀린에서는 필요 없을 것 같네요~

2023-03-23 12:33 UTC, f-lab-kyucumber commented on build.gradle.kts
> +    runtimeOnly("com.mysql:mysql-connector-j")
mysql connector j를 사용하신 이유가 있나요?
현업에서는 AWS Aurora를 많이 사용해서 mariadb connector를 많이 사용하는 편입니다.
이것도 3.x.x부터는 aurora failover나 read writer 분산이 없어져서 2.7.x로 낮춰서 사용하고 있긴 하지만요.. 😭

2023-03-23 12:33 UTC, f-lab-kyucumber commented on build.gradle.kts
> +plugins {
이번은 마지막 프로젝트인데요.

현업에서도 대부분 멀티 모듈을 사용합니다. 멀티 모듈 구조를 사용해보시는건 어떨까요?

2023-03-23 12:33 UTC, f-lab-kyucumber commented on run.sh
> +./gradlew bootRun -PskipDownload=true -Dspring.profiles.active=dev
dockerfile에서 요걸 실행하는것 같은데 jar를 카피한 뒤 java jar 명령어를 사용하는게 아니라 ./gradlew로 실행하는 이유가 있을까요?

그냥 초기라 요렇게 해두신걸까요?

2023-03-23 12:33 UTC, f-lab-kyucumber commented on src/main/kotlin/com/flab/artshare/config/security/FirebaseAuthFilter.kt
> +        request.getHeader("Authorization")?.takeIf { it.startsWith("Bearer ") }?.substring(7)
요런 scope 함수들을 언제 쓰냐에 대한건 논란이 있지만 아래 문서를 한번 읽어보셔도 좋을 것 같네요.

https://medium.com/@limgyumin/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%98-takeif-takeunless-%EB%8A%94-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94%EA%B0%80-f6637987780

2023-03-23 12:33 UTC, f-lab-kyucumber commented on src/main/kotlin/com/flab/artshare/config/security/SecurityConfig.kt
> +    fun filterChain(http: HttpSecurity): SecurityFilterChain {
아래 문서를 한번 읽어보시고 kotlin DSL 형태로 security config를 정의해보셔도 좋겠네요.

https://spring.io/blog/2020/03/04/spring-tips-kotlin-and-spring-security
https://docs.spring.io/spring-security/reference/servlet/configuration/kotlin.html#page-title

2023-03-23 12:33 UTC, f-lab-kyucumber commented on src/main/kotlin/com/flab/artshare/config/security/UnauthorizedEntryPoint.kt
> +@Component
줄바꿈이 필요해보여요.

2023-03-23 12:33 UTC, f-lab-kyucumber commented on src/test/kotlin/com/flab/artshare/ArtShareApplicationTests.kt
> +@ActiveProfiles("local")
요 테스트는 어느 환경이든 다 통과되어야 할 것 같은데요. local로 제한을 주신 이유가 있을까요?

2023-03-23 13:36 UTC, gimseonjin commented on run.sh
> +./gradlew bootRun -PskipDownload=true -Dspring.profiles.active=dev
firebase emulator 쓰려고 하면 설치도 해야하고 또 terminal 환경변수를 사용해야합니다

export FIREBASE_AUTH_EMULATOR_HOST=localhost:9099

이런 식으로 해줘야 하는데 매번 하기 귀찮고 또 하지 않으면 버그가 나서 docker-compose로 서버 띄우면 자동으로 firebase emulator랑 연동되게 설정했습니다.

그 과정에서 코드 변경될 때 마다 재시작하기 번거로우니까 bootRun으로 실행해서 코드 변경 감지해서 도커 내부의 class 파일을 바꿔주는 식으로 개발 환경을 구축해봤습니다!!!

설명이 조금 장황한데 결론은 이 file은 개발할 때 쓰는 겁니다!

2023-03-23 13:37 UTC, gimseonjin commented on src/test/kotlin/com/flab/artshare/ArtShareApplicationTests.kt
> +@ActiveProfiles("local")
그 test를 돌릴 때, firebase 설정값이 들어가야하는데 default인 경우에는 firebase.json 환경을 못찾아서 우선 local로 설정하고 나중엔 test 환경을 세팅하려고 합니다!

2023-03-23 14:14 UTC, jaeyeonme commented on .editorconfig
> +[*.{kt,kts}]
trailing comma 관련 찾아보다가 2가지 설정이 있는 것으로 확인을 하였는데요.
`ij_kotlin_allow_trailing_comma_on_call_site` 설정도 같이 허용을 하시나요?

2023-03-25 04:59 UTC, gimseonjin commented on build.gradle.kts
> +    runtimeOnly("com.mysql:mysql-connector-j")
이 부분은 spring boot initializer를 사용해서 만든 거라 default 세팅으로 됐습니다!!

저희 db도 naver cloud 껄 쓰지 싶은데 거기도 mariadb 기반으로 알고 있어서 이거도 수정해놓겠습니다!

2023-03-25 05:00 UTC, gimseonjin commented on build.gradle.kts
> +    annotationProcessor("org.projectlombok:lombok")
네 수정하겠습니다!!

2023-03-25 05:17 UTC, gimseonjin commented on src/main/kotlin/com/flab/artshare/config/security/SecurityConfig.kt
> +    fun filterChain(http: HttpSecurity): SecurityFilterChain {
멘토님!! 멘토님이 주신 링크는 webflux 기반으로 해야 동작한다고 하는데 

음 webflux로 전환할까요??

2023-03-25 05:17 UTC, gimseonjin commented on src/main/kotlin/com/flab/artshare/config/security/UnauthorizedEntryPoint.kt
> +@Component
확인했습니다!

2023-03-25 05:19 UTC, gimseonjin commented on build.gradle.kts
> +    annotationProcessor("org.projectlombok:lombok")
확인했습니다!

2023-03-25 05:20 UTC, gimseonjin commented on build.gradle.kts
> +    runtimeOnly("com.mysql:mysql-connector-j")
스프링부트 이니셜라이저에서 제공하는 default 설정을 사용한 것입니다!!

저희 나중에 naver cloud에서 서버를 만들어 쓸 거 같은데 거기도 mariadb 베이스인 거 같아서

mariadb connector로 사용하겠습니다!

2023-03-25 05:21 UTC, gimseonjin commented on build.gradle.kts
> +plugins {
멀티 모듈은 저희 둘 다 써보지 않아서 우선 재현님과 의논해보겠습니다!

2023-03-25 06:11 UTC, gimseonjin commented on src/main/kotlin/com/flab/artshare/config/security/FirebaseAuthFilter.kt
> +        request.getHeader("Authorization")?.takeIf { it.startsWith("Bearer ") }?.substring(7)
음~ takeIf는 값을 반환할 때 optional 처럼 사용하는군요!

지금 같은 경우에는 값을 반환하거나 에러를 띄우는 상황이기 때문에 if 문이 더 나은 거 같습니다

수정하겠습니다!

2023-03-28 11:54 UTC, gimseonjin commented on build.gradle.kts
> +plugins {
의논 결과 현재 msp 기능 구현도 많이 늦어져서 멀티 모듈은 최소 기능 구현 끝나고 적용해보는 걸로 햇습니다!

2023-03-28 12:23 UTC, kyucumber commented on .editorconfig
> +[*.{kt,kts}]
저는 해당 설정은 쓰지 않습니다.

2023-03-28 12:24 UTC, f-lab-kyucumber commented on .editorconfig
> +[*.{kt,kts}]
저는 해당 옵션은 쓰지 않습니다.

2023-03-28 12:24 UTC, f-lab-kyucumber commented on build.gradle.kts
> +plugins {
멀티 모듈이 적용된 시점과 아닌 시점에 설계가 많이 달라집니다.
가급적이면 시작부터 적용해보시고 멀티 모듈로 나뉘어진 상황에서의 설계를 고민해보시면 좋을것 같다는 의견이 있네요.

2023-03-28 12:33 UTC, f-lab-kyucumber commented on src/main/kotlin/com/flab/artshare/config/security/SecurityConfig.kt
> +    fun filterChain(http: HttpSecurity): SecurityFilterChain {
어디에 그런 내용이 있나요? 제가 드린 가이드 문서 링크가 Servlet Application 기반이에요.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/107192309/228237102-515acd49-0434-4360-8838-370ed9a48b05.png">

Reactive 가이드 문서 링크는 따로 있었던거 같은데요.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/107192309/228237278-caa24f31-efa1-420c-b54c-e6247747bae1.png">

2023-03-28 12:47 UTC, f-lab-kyucumber requested changes

2023-03-28 12:47 UTC, f-lab-kyucumber commented on run.sh
> +./gradlew bootRun -PskipDownload=true -Dspring.profiles.active=dev
firebase admin sdk 의존성이 어떤식으로 구성되어 있는지 몰라서 확신은 없는데 firebase emulator의 경우 한번 설정해서 컨테이너로 띄워두면 애플리케이션 코드 변경에 대한 재시작과는 무관하지 않나요?

애플리케이션에서 필요한건 아래 두가지 값 같은데요.

1. FIREBASE_AUTH_EMULATOR_HOST 환경 변수
2. firebaseAdminSdkPath

mysql이랑 firebase emulator 컨테이너를 띄우기 위한 부분을 추출하고 애플리케이션은 intelliJ 런타임을 쓰는게 편하게 개발할 수 있지 않을까 해서요. 요건 멘토링 시간에 조금 더 구체적으로 질문 드리겠습니다.

2023-03-28 12:47 UTC, f-lab-kyucumber commented on docker-compose.yaml
> +  mariadb:
mariaDB 커넥터를 쓴다고 mariaDB를 써야하는건 아닙니다. 
혹시 커넥터 때문에 바꾸신거면 MySQL을 사용하셔도 무관합니다.

2023-03-28 12:47 UTC, f-lab-kyucumber commented on src/test/kotlin/com/flab/artshare/ArtShareApplicationTests.kt
> +@ActiveProfiles("local")
요건 개인적인 궁금증이 있어 질문드리는건데 firebase admin sdk를 써보지 않았는데 연결에 실패하면 아예 앱 구동이 실패하나요? 이후에 firebase 관련 설정을 빼고 스프링 컨텍스트를 띄우시려는걸까요?

2023-04-01 12:03 UTC, jaeyeonme commented on build.gradle.kts
> +plugins {
그러면 다음 PR에서 멀티모듈로 따로 올리겠습니다.

2023-04-02 05:36 UTC, f-lab-kyucumber approved these changes

2023-04-02 05:36 UTC, f-lab-kyucumber commented on src/main/kotlin/com/flab/artshare/config/firebase/FirebaseConfig.kt
> +        return if (activeProfile == "local" || activeProfile == "test")
이런식으로 런타임에 profile에 따라 바뀌는 코드를 운영에서도 사용할 수 있도록 하면 버그가 발생하기 쉬울 것 같아요.
한번 정의되면 바뀌진 않겠지만 여기처럼 profile이 연관된 부분은 아예 추출해서 분리해도 좋을 것 같아요.

2023-04-02 05:36 UTC, f-lab-kyucumber commented on src/main/kotlin/com/flab/artshare/config/security/SecurityConfig.kt
> +            .build()
이 부분은 따로 코멘트를 안 남겨두셨는데
https://github.com/f-lab-edu/art-share/pull/13/files#r1148307396
위에 말씀하신 부분과 관련해서 관련한 링크 등을 알려주실 수 있나요?

그리고 큰 의미를 두고 하신 말씀은 아닐거라 생각하지만, 단순히 이 설정을 적용하기 위해 WebFlux를 적용할까요? 하고 질문주셨는데요. 이런 의사결정 방법이 바람직한 방법인지에 대해 고민이 필요할 것 같아요. 🙂

2023-04-02 05:50 UTC, gimseonjin commented on src/main/kotlin/com/flab/artshare/config/security/SecurityConfig.kt
> +            .build()
헉 이부분 제가 코멘트 단 줄 알았는데 안달았군요 ㅜㅜ 죄송합니다

다른 게 아니라 설정하는데 아래와 같이 에러가 계속 떠서 찾아보니 webflux 아니면 저런 에러가 뜬다는 글을 본적이 있어서요(지금은 못찾았습니다)

그 후에 계속 리서치 하다가 잊어버렸습니다! 일단 오늘 계속 더 찾아보겠습니다~


<img width="540" alt="image" src="https://user-images.githubusercontent.com/66009926/229334226-95697704-b35d-4c4d-96c8-8654de967a25.png">

2023-04-02 07:57 UTC, merged