feat: Set Multi Module
f-lab-edu/art-share pull request #22
Opened 2023-04-16 06:17 UTC by gimseonjin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature

## What is the current behavior?

Issue Number: #21 

## What is the new behavior?

## PR information

기존 프로젝트 세팅을 멀티 모듈 방식으로 수정했습니다!

api <- domain <- external 순으로 의존성을 가지고 있고 spring security에서 fierbase 의존성을 때내서 external로 옮겼고 그 과정에서 코드가 추가됐습니다.

2023-04-16 11:18 UTC, kyucumber requested changes

2023-04-16 11:18 UTC, kyucumber commented on .editorconfig
>  # 이는 ktlint의 import-ordering 규칙과 맞지 않는다.
java.* 형태로 import 하는거 자체가 lint에서 권장하는 형태는 아닙니다.

2023-04-16 11:18 UTC, kyucumber commented on art-api/build.gradle.kts
> +}
중복해서 들어가있네요.

2023-04-16 11:18 UTC, kyucumber commented on art-api/build.gradle.kts
> +}
아래 형태로도 사용할 수 있을거에요.

```kotlin
tasks.jar { enabled = true }
tasks.bootJar { enabled = false }
```

2023-04-16 11:18 UTC, kyucumber commented on art-domain/build.gradle.kts
> +}
요거 다 중복해서 정의되어 있는데요.

루트의 build.gradle에 정의하면 어떨까요?

```kotlin
subprojects {
        tasks {
            jar { enabled = true }
            bootJar { enabled = false }
        }
}
```

그리고 배포가 필요한 모듈에서만 override 하는 형태로 사용할 수 있습니다.

2023-04-16 11:18 UTC, kyucumber commented on art-domain/src/main/kotlin/com/flab/artshare/AuthService.kt
> +package com.flab.artshare
domain 모듈의 스프링 컨텍스트에 이상 유무를 판단하기 위해 도메인 모듈에도 SpringBootTest로 되어있는 테스트를 하나 넣어주시면 어떨까요?

여기는 스프링 부트 애플리케이션이 올라오지 않을거라 아래와 같이 기존에 작성하시던 형태랑 조금 다르게 하셔야 할 거에요.

```kotlin
@SpringBootApplication
@SpringBootTest
class ArtDomaintest : DescribeSpec() {
    override fun extensions() = listOf(SpringExtension)

    init {
        describe("contextLoads") {
            it("~~") {}
        }
    }
}

```

2023-04-16 11:18 UTC, kyucumber commented on build.gradle.kts
>  import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
중요한 부분은 아닌데 buildSrc를 활용해보셔도 좋을 것 같네요.

https://sabarada.tistory.com/203

2023-04-16 11:18 UTC, kyucumber commented on art-external/src/main/kotlin/com/flab/artshare/firebase/FirebaseInitializer.kt
> +        println(config)
log로 변경하시거나 불필요한 코드면 제거해주세요.

2023-04-16 11:18 UTC, kyucumber commented on build.gradle.kts
> +        implementation("org.jetbrains.kotlin:kotlin-reflect")
중요한건 아닌데 jackson-module-kotlin에 kotlin-relfect가 포함되어 있어서 굳이 import 하지 않아도 괜찮긴 해요.

```
+--- com.fasterxml.jackson.module:jackson-module-kotlin -> 2.13.5
|    +--- org.jetbrains.kotlin:kotlin-reflect:1.5.32 -> 1.7.10

```

2023-04-16 11:26 UTC, jaeyeonme commented on .editorconfig
>  # 이는 ktlint의 import-ordering 규칙과 맞지 않는다.
`./gradlew ktlintFormat` 을 하게 되면 `import javax.persistence.*` 이렇게 WildCard 로 나오면서 build error 가 나오게 됩니다. 이런 경우는 어떡게 처리를 하시나요?!

2023-04-16 11:28 UTC, jaeyeonme commented on art-api/build.gradle.kts
> +}
중복 제거 하겠습니다.

2023-04-19 12:24 UTC, jaeyeonme commented on art-api/build.gradle.kts
> +}
이걸로 바꿔보겠습니다.

2023-04-19 12:24 UTC, jaeyeonme commented on art-domain/build.gradle.kts
> +}
수정해보겠습니다.

2023-04-24 09:37 UTC, gimseonjin commented on build.gradle.kts
>  import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
이 부분은 중요한 게 아닌 듯하고 다른 기능 구현이 밀려있어서 생략하거나 나중에 수정하도록 하겠습니다!!

2023-04-24 09:45 UTC, merged

2023-04-27 08:19 UTC, jaeyeonme commented on art-api/build.gradle.kts
> +}
@kyucumber 이 설정에 대해 질문이 있습니다.

```kotlin
tasks.jar { enabled = true }
tasks.bootJar { enabled = false }
```

일반적으로 Spring Boot 프로젝트에서는 bootJar 작업을 사용하여 실행 가능한 JAR 파일을 생성합니다. 그러나 멀티모듈 프로젝트의 경우, 각 모듈이 독립적인 실행 가능한 JAR를 만들지 않고, 하나의 실행 가능한 JAR를 생성하는 것이 일반적인가요?

이런 경우에는 하나의 모듈(보통 루트 모듈이나 메인 모듈)에서만 bootJar를 사용하고, 나머지 모듈에서는 jar 작업을 사용하여 JAR 파일을 생성할 수 있습니다.

그래서 루트 모듈에서는
```kotlin
tasks.jar { enabled = false }
tasks.bootJar { enabled = true }
```

다른 모듈들은
```kotlin
tasks.jar { enabled = true }
tasks.bootJar { enabled = false }
```

이렇게 설정하나요?!