#10 swagger 세팅
f-lab-edu/art-share pull request #24
Opened 2023-04-30 08:57 UTC by jaeyeonme

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature

## What is the current behavior?

Issue Number: #10 

## What is the new behavior?

## PR information
- Swagger 설정
- 의존성 관리를 위해 buildSrc 적용

2023-04-30 12:32 UTC, kyucumber requested changes

2023-04-30 12:32 UTC, kyucumber commented on config/detekt.yml
> +        # - 'KtFileCountProcessor'
불필요한건 주석으로 남기지 않고 제거해도 되지 않을까요?

2023-04-30 12:32 UTC, kyucumber commented on build.gradle.kts
> +    }
detekt를 실제로 구동하기 위한 task도 추가해주시면 어떨까요?

그리고 pre-commit hook 혹은 CI에 연동을 해주시는게 어떨까 합니다.

```kotlin
val detektFormat by tasks.registering(io.gitlab.arturbosch.detekt.Detekt::class) {
    // detekt 포맷팅을 위한 task
    config.setFrom(files(projectDir.resolve("config/detekt/detekt.yml")))
}

val detektAll by tasks.registering(io.gitlab.arturbosch.detekt.Detekt::class) {
    // detekt 정적 분석을 돌리고 그에 대한 성공 / 실패 여부를 반환하는 task
    config.setFrom(files(projectDir.resolve("config/detekt/detekt.yml")))
}
```

2023-04-30 12:32 UTC, kyucumber commented on buildSrc/build.gradle.kts
> +}
여기에 아래와 같이 dependency management plugin을 넣는 경우도 있으니 참고 부탁드립니다.

```kotlin
dependencies {
    implementation("io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE")
}
```

2023-04-30 12:32 UTC, kyucumber commented on art-api/src/main/kotlin/com/flab/artshare/config/swagger/SwaggerConfig.kt
> +        .build()
Swagger를 쓰고 public으로 여는 경우에 POST나 PUT 등의 요청을 외부에서 실행할 수 있을 것 같은데요.

Swagger에 대한 경로 등에 대해 인증 등을 신경써주시면 좋을 것 같아요.

2023-04-30 12:52 UTC, jaeyeonme commented on config/detekt.yml
> +        # - 'KtFileCountProcessor'
넵 제거하겠습니다!

2023-04-30 13:31 UTC, jaeyeonme commented on build.gradle.kts
> +    }
CI에 연동해보겠습니다!

2023-04-30 14:09 UTC, jaeyeonme commented on buildSrc/build.gradle.kts
> +}
이걸로 한번 교체해보겠습니다~

2023-04-30 15:17 UTC, jaeyeonme commented on art-api/src/main/kotlin/com/flab/artshare/config/swagger/SwaggerConfig.kt
> +        .build()
SecurityConfig 에 Swagger 경로를 추가했습니다!

2023-05-02 11:56 UTC, f-lab-kyucumber commented on .github/workflows/build.yml
> +                    echo $dest >> $GITHUB_PATH
이거 설치하지 않고 ./gradlew detekt와 같이 gradle task를 활용할 수 있을 것 같아요.

2023-05-02 13:03 UTC, jaeyeonme commented on .github/workflows/build.yml
> +                    echo $dest >> $GITHUB_PATH
넵 다시 수정해봤습니다!

2023-05-03 12:08 UTC, f-lab-kyucumber commented on .github/workflows/build.yml
> +                run: ./gradlew detekt
detektAll task를 별도로 만드셨던데 detekt를 호출하고 있는 것 같아요.

불필요하다면 detektAll task를 제거하거나 detektAll을 호출하도록 변경해주시는게 좋을 것 같아요.

2023-05-03 12:08 UTC, f-lab-kyucumber approved these changes

2023-05-03 12:10 UTC, jaeyeonme commented on .github/workflows/build.yml
> +                run: ./gradlew detekt
우선 제거하는 방향으로 해보겠습니다.

2023-05-04 02:22 UTC, merged