add : Naver Check Style 및 JaCoCo 설정
f-lab-edu/art-share pull request #8
Opened 2023-03-12 16:07 UTC by jaeyeonme

2023-03-12 16:09 UTC, jaeyeonme commented
> There is no coverage information present for the Files changed

|Total Project Coverage|20%|:x:|
|:-|:-:|:-:|

2023-03-13 05:34 UTC, jaeyeonme commented
> There is no coverage information present for the Files changed

|Total Project Coverage|20%|:x:|
|:-|:-:|:-:|

2023-03-13 11:18 UTC, gimseonjin reviewed
@jaeyeonme 이거 JAVA용인가여?? Kotlin도 되요??

2023-03-13 14:00 UTC, gimseonjin reviewed
@jaeyeonme 이거 JAVA용인가여?? Kotlin도 되요??

2023-03-13 14:00 UTC, gimseonjin commented on .github/workflows/build.yml
> +      - name: Checkstyle
./gradlew ktlintCheck

2023-03-13 14:06 UTC, jaeyeonme commented
> There is no coverage information present for the Files changed

|Total Project Coverage|20%|:x:|
|:-|:-:|:-:|

2023-03-13 14:12 UTC, jaeyeonme commented
|File|Coverage [20%]|:x:|
|:-|:-:|:-:|
|[ArtShareApplication.kt](https://github.com/f-lab-edu/art-share/blob/453224eda00d0aac0f9ed0a3fc5e9e95e88a43f2/src%2Fmain%2Fkotlin%2Fcom%2Fflab%2Fartshare%2FArtShareApplication.kt)|20%|:x:|

|Total Project Coverage|20%|:x:|
|:-|:-:|:-:|

2023-03-13 14:14 UTC, jaeyeonme commented
|File|Coverage [20%]|:x:|
|:-|:-:|:-:|
|[ArtShareApplication.kt](https://github.com/f-lab-edu/art-share/blob/2f6efdde011ecf505c9af9c1b48b62fff033bec5/src%2Fmain%2Fkotlin%2Fcom%2Fflab%2Fartshare%2FArtShareApplication.kt)|20%|:x:|

|Total Project Coverage|20%|:x:|
|:-|:-:|:-:|

2023-03-13 14:19 UTC, jaeyeonme commented
|File|Coverage [20%]|:x:|
|:-|:-:|:-:|
|[ArtShareApplication.kt](https://github.com/f-lab-edu/art-share/blob/453e99a352b13341cc5a83b71e3b294abec0e685/src%2Fmain%2Fkotlin%2Fcom%2Fflab%2Fartshare%2FArtShareApplication.kt)|20%|:x:|

|Total Project Coverage|20%|:x:|
|:-|:-:|:-:|

2023-03-15 08:36 UTC, jaeyeonme commented
|File|Coverage [20%]|:x:|
|:-|:-:|:-:|
|[ArtShareApplication.kt](https://github.com/f-lab-edu/art-share/blob/995a2ec31180d834949b3133dd3d8556bc6f3744/src%2Fmain%2Fkotlin%2Fcom%2Fflab%2Fartshare%2FArtShareApplication.kt)|20%|:x:|

|Total Project Coverage|20%|:x:|
|:-|:-:|:-:|

2023-03-16 12:28 UTC, f-lab-kyucumber requested changes

2023-03-16 12:28 UTC, f-lab-kyucumber commented on .github/workflows/build.yml
> +        id: jacoco
kotlin에서는 jacoco 대신 kover를 사용해보셔도 좋을 것 같네요.

https://github.com/Kotlin/kotlinx-kover

2023-03-16 12:28 UTC, f-lab-kyucumber commented on build.gradle
>  import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
build.gradle도 kotlin으로 설정해보시면 좋겠습니다.

2023-03-16 12:28 UTC, f-lab-kyucumber commented on Dockerfile
> +CMD [ "sh" , "run.sh" ]
java 11인데 docker base image는 openjdk 17이네요? openjdk11을 사용하는게 어떨까요.

2023-03-16 12:28 UTC, f-lab-kyucumber commented on Dockerfile
> +CMD [ "sh" , "run.sh" ]
여기서 실행하시는 run.sh 파일이 보이지 않는데요. 이후에 추가하실 예정인걸까요?

2023-03-16 12:28 UTC, f-lab-kyucumber commented on build.gradle
>  }
buildSrc를 사용해보셔도 좋을 것 같네요.

https://sabarada.tistory.com/203
https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources

2023-03-16 12:28 UTC, f-lab-kyucumber commented on build.gradle
> +    testImplementation 'org.springframework.boot:spring-boot-starter-test'
kotest에 대해 살펴보시고 kotest를 사용해보시면 좋을 것 같네요.

kotest는 junit의 assertion과 어떤 것이 다른지, 왜 사용해야하는지 등도 한번 같이 살펴보세요.

2023-03-16 12:28 UTC, f-lab-kyucumber commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.jpa' version '1.5.30'
이 두 플러그인은 왜 추가해야 할까요? 혹시 알고 계시나요?

2023-03-16 16:05 UTC, gimseonjin commented on Dockerfile
> +CMD [ "sh" , "run.sh" ]
아 openjdk11 했는데 gradle 빌드가 깨지더라구요 이유는 모르겠는데 17하니까 빌드가 되서 우선 이렇게 진행했습니다

그리고 run.sh 파일은 다음 pr 때 포함되서 나갈겁니다!! 다음부터는 pr 범위 잘 조정해서 올리겠습니다!

2023-03-16 16:10 UTC, gimseonjin commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.jpa' version '1.5.30'
이거 전에 말씀해주신 kotlin 상속 & proxy 구현에 필요한 것으로 알고있습니다!

2023-03-16 17:07 UTC, jaeyeonme commented on build.gradle
>  }
넵 확인했습니다!

2023-03-16 17:07 UTC, jaeyeonme commented on build.gradle
>  import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
이것도 수정하겠습니다~

2023-03-16 17:11 UTC, jaeyeonme commented on .github/workflows/build.yml
> +        id: jacoco
이것도 kover로 수정해보겠습니다.

2023-03-17 06:51 UTC, jaeyeonme commented
|File|Coverage [20%]|:x:|
|:-|:-:|:-:|
|[ArtShareApplication.kt](https://github.com/f-lab-edu/art-share/blob/995a2ec31180d834949b3133dd3d8556bc6f3744/src%2Fmain%2Fkotlin%2Fcom%2Fflab%2Fartshare%2FArtShareApplication.kt)|20%|:x:|

|Total Project Coverage|20%|:x:|
|:-|:-:|:-:|

2023-03-17 08:11 UTC, jaeyeonme commented on build.gradle
>  import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
`build.gradel` 이 Groovy를 사용하는 것으로 알고 있는데 `build.gradle.kts` 를 말씀하시는게 맞을까요?!

2023-03-19 03:37 UTC, jaeyeonme commented on build.gradle
> +    testImplementation 'org.springframework.boot:spring-boot-starter-test'
찾아봤습니다!
- 다양한 Assertion 라이브러리 지원
- DSL을 활용한 가독성 높은 테스트 코드 작성
- Fixture 함수를 통한 중복 제거와 테스트 코드 작성의 간소화
- Test Interceptors를 통한 테스트 실행 전/후에 추가적인 로직 적용 가능
- Gradle 및 Maven과 같은 빌드 도구와 연동하여 사용 가능

2023-03-20 02:47 UTC, f-lab-kyucumber commented on build.gradle
>  import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
네 맞습니다.

2023-03-20 02:49 UTC, f-lab-kyucumber commented on build.gradle
> +    testImplementation 'org.springframework.boot:spring-boot-starter-test'
네 junit을 사용하게 되면 테스트 코드가 메인 코드인 코틀린과 맞지 않는 부분이 생깁니다.(DSL을 적용할 수 없는 등)
시간 나시면 아래 글도 한번 읽어보세요.

https://techblog.woowahan.com/5825/

2023-03-20 02:50 UTC, f-lab-kyucumber commented on build.gradle.kts
> +}
요건 추가하신 이유가 무엇일까요~?

2023-03-20 02:53 UTC, f-lab-kyucumber commented on build.gradle.kts
> +}
이 2가지 태스크는 추가하신 이유가 무엇일까요~?

2023-03-20 02:53 UTC, f-lab-kyucumber commented on .gitignore
> +.editorconfig
.editorconfig는 보통 git에 같이 올려서 협업하는 구성원들과 공유하는데요. 요걸 제외하신 이유가 있을까요?

2023-03-20 02:56 UTC, f-lab-kyucumber commented on build.gradle.kts
> +    }
kover의 jvm 예제를 보면 좀 간소화된 부분도 있는데요, 이 설정들이 다 필요한게 맞을까요? 조금 줄여볼 순 없을까요?

https://github.com/Kotlin/kotlinx-kover/blob/main/examples/jvm/merged/build.gradle.kts

2023-03-20 02:57 UTC, f-lab-kyucumber approved these changes

2023-03-20 03:16 UTC, gimseonjin commented on build.gradle.kts
> +}
이 부분은 다음 pr에 올라가야할 내용인데 저희가 dev 환경을 docker-compose로 만들어서 dev-tools가 로컬 코드 변경을 감지해서 도커 컨테이너 변경을 자동으로 할 수 있게금 하기 위해 추가했습니다!!

2023-03-20 03:17 UTC, gimseonjin commented on .gitignore
> +.editorconfig
이건 다시 제외해놓겠습니다

2023-03-20 03:18 UTC, jaeyeonme commented on .gitignore
> +.editorconfig
앗 그렇군요! 올라가면 안되는 건 줄 알고 넣었습니다. 제외하도록 하겠습니다.

2023-03-20 03:18 UTC, jaeyeonme commented on build.gradle.kts
> +}
docker-compose.yml 파일에서 `docker-compose up --build` 를 실행하게 되면 

 ERROR [4/4] RUN chmod +x run.sh && ./gradlew updateLib                                                                                                             233.0s                                                                                                                                                           
 > [4/4] RUN chmod +x run.sh && ./gradlew updateLib:                 

 
 Task 'buildAndReload' not found in root project 'ArtShare'.

라는 이름의 작업이 `build.gradle.kts` 파일에 정의되어 있지 않기 떄문에 발생하는 오류라고 확인하고 `build.gradle.kts` 파일에 추가했습니다!

2023-03-20 03:18 UTC, jaeyeonme commented on build.gradle.kts
> +    }
이부분도 줄여보도록 하겠습니다!

2023-03-20 07:15 UTC, merged